name: Test Environment

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '22'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Generate Gradle Wrapper
        run: gradle wrapper

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Run  Tests
        run: ./gradlew test --tests --no-configuration-cache

      # Checkout previous GitHub Pages branch (contains previous report)
      - name: Checkout gh-pages branch
        if: always()
        continue-on-error: true
        uses: actions/checkout@v5
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy Allure History
        if: always()
        run: |
          mkdir -p build/allure-results/history
          if [ -d "gh-pages/last-history" ]; then
            cp -R gh-pages/last-history/* build/allure-results/history/
          fi

      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: build/allure-results
          allure_report: allure-report
          gh_pages: gh-pages
          allure_history: allure-history

      # Upload report as artifact
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      # Deploy report to GitHub Pages
      - name: Deploy Allure Report
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: allure-history
          token: ${{ secrets.GITHUB_TOKEN }}